### ISSUE TITLE
JHipster 3.0 compatibility

### ISSUE THREAD

**Issue by tomvanrossom** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#13]
Is this module compatible with JHipster 3.0? No: any planned dates yet?

**Comment by geraldhumphries** [comment]
I just tested it out with JHipster 3.0, and it seems to work great already! The files are being generated and post-creation hooks are working properly. This is working without any changes because it doesn't actually hook into JHipster functions that may change between versions - it simply reads the entity json files in `.jhipster`.

If you do run into problems, open a new issue to let me know.
