### ISSUE TITLE
Automatic reindexAll using @PostConstruct

### ISSUE THREAD

**Issue by jeyakumarsm** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#19]
Hi, first of all, thanks a lot for your reindexer. What do you think about invoking reindexAll after server startup so that reindexing is done automatically without admin doing manually? This can solve 2 issues: 1) In the UI, if you search for an entity where there is no row inserted in database, elastic search server will throw error which will be shown as internal server error in the UI. 2) Entity resource tests invoke *SearchRepository.deleteAll() in initTest() method which throws exception saying no index found. How about this code in ElasticsearchIndexService.java itself?

`@PostConstruct
    public void reindexAllAfterServerStartup(){
    	this.reindexAll();
    }`

I could be wrong, please see if you can throw some light on this.

**Comment by geraldhumphries** [comment]
Rebuilding the index is something that can take a very long time, and a lot of people wouldn't want this to run on startup, especially in production.

In production, ES indexes are not intended to be rebuilt often - they should be persistent like a database. However when developing, ES data is stored in the `target` folder. This data is deleted when running `gradle clean` or `mvn clean` which is why you see those errors on searches.

It's not a bad idea for tests though. Any data loaded with Liquibase will be available in the indexes while testing, which is a good thing. Maybe this functionality should be available as an option, for tests only?

If the resource tests run `deleteAll()` and can sometimes throw errors, then that is a problem with the tests themselves and they should be fixed. If the code that throws this error is generated you should report the issue in the main JHipster project.

**Comment by geraldhumphries** [comment]
I am closing this issue because this is a feature that I don't believe should be implemented.
