### ISSUE TITLE
Add Angular 2 app support

### ISSUE THREAD

**Issue by geraldhumphries** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#22]
JH added Angular 2 support in version 4. Following #21, A2 frontend files should be added.

**Comment by pascalgrimaud** [comment]
Hi @geraldhumphries 

Currently, I need this for one of my project.
So I already started to work on this. As soon as it's finished, I will pull request the front part for Angular4.

As I'm learning Angular4, don't expect a PR the next weeks, I will take my time to finish it properly. But as there are no comment since the 22 Feb, I suppose it is not so urgent.

Just wanted to let you know it.

**Comment by geraldhumphries** [comment]
Awesome, thank you!

**Comment by pascalgrimaud** [comment]
I got everything working. 

I need to PR first a needle to the main generator-jhipster then I will PR here.
