### ISSUE TITLE
Reindex in groups instead of all

### ISSUE THREAD

**Issue by tomcgn** [geraldhumphries/generator-jhipster-elasticsearch-reindexer#37]
I experienced exceptions during reindexing (v 1.0.2) with high number of instances, especially when these contained clob / lob / blob. 
Re-Indexing works comparably fast, if performed in bunches of, say, 1000 objects. This can easily be achieved by adding a Pageable as parameter.

Change in method `reindexForClass` :

```java
...
 if (jpaRepository.count() > 0) {
            log.info(entityClass + ":  " + jpaRepository.count());
            int size = 100;
            for (int i = 0; i <= jpaRepository.count() / size; i++) {
                Pageable page = new PageRequest(i, size);
                log.info("Indexing page : " + i + " , nr " + size);
                try {
                    Method m = jpaRepository.getClass().getMethod("findAllWithEagerRelationships", Pageable.class);
                    List<T> paged = (List<T>) m.invoke(jpaRepository, page);
                    elasticsearchRepository.save(paged);
                }

                catch (NoSuchMethodException ex) {
                    log.info(ex.getLocalizedMessage());
                    elasticsearchRepository.save(jpaRepository.findAll(page));
                } catch (Exception ex) {
                    log.error(ex.getMessage());
                    ex.printStackTrace(System.out);
                }
            }
        }
...
```

**Comment by geraldhumphries** [comment]
I assume you are getting `java.lang.OutOfMemoryError: GC overhead limit exceeded`?

Two problems here: 

1. `findAllWithEagerRelationships` is never generated with a Pageable parameter (as far as I'm aware), so if we want to use it we'll need to overload it by modifying the Repository interfaces for each entity.
2. Combining pagination with joins (the initialization method used by `findAllWithEagerRelationships`) causes in-memory pagination. This is because the result set is a cartesian product making it impossible to use sql-based pagination. This is the reason `findAllWithEagerRelationships` is never generated with pagination params. I have seen this cause a request to get a page of 10 entities take over 5 minutes.

@FireWolf2007 presented a solution in #17 that I think might work well. I will need to test it out.

**Comment by tomcgn** [comment]
The expection was not `java.lang.OutOfMemoryError` but related to undertow that had a limit of around 850 Mb, while the result set was >1Gb. 
And yes, you'd need to overload the 'findAllWithEagerRelationships', but the 'findAll' fallback should always work.

**Comment by geraldhumphries** [comment]
You are right, we should definitely be using pagination for entities that don't need eager many-to-many relationships. No reason not to.

However there's no easy solution for entities that do need those relationships. Reading the entity configuration files and manually initializing relationships might be our only option.
